# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b66ad63f53eb65b50f098c3990cc3a5a380f44666837aeefaaabe50b3b1b0b5a7e0dcbe36ea6565c93ed2ff649dfb3f24067de13e5bb02c1100caa139af67c

test:
  secret_key_base: 62f03032f2d3d2e459bdb22305580cabf403d11ef8154d6893945120f7ad2e8a6269a9e2c9032f61a39fd343027d9c25d557148e5e4796aa2aff874babbfc1b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
